databases:
  - name: video-db
    plan: free

services:
  - type: web
    name: video-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd backend && ./start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: video-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: video-redis
          property: connectionString

  - type: redis
    name: video-redis
    plan: free
    ipAllowList: []
